#!/bin/bash
#
# skript 2 oma andmetega
#
# skripti algus
who | awk -F ' tty*' '{print $1}' > nimed #otsib nimed
cat nimed | awk -F '.' '{print $2"."$1}' > nimed2 #paneb nimed kokku
cat nimed2 | sort | uniq #prindib sorteeritud nimed
#
# skripti lõpp

